# Use Nginx to serve React build
FROM nginx:stable

# Copy build files to Nginx HTML folder
COPY build/ /usr/share/nginx/html

# Copy Nginx config
COPY ../nginx/chatapp-docker.conf /etc/nginx/conf.d/default.conf

# Expose HTTP port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
