# Use Eclipse Temurin JDK 21
FROM eclipse-temurin:21-jdk

# Set working directory
WORKDIR /app

# Copy your built jar into the container
COPY *.jar app.jar

# Expose the internal container port
EXPOSE 8081

# Run the app
CMD ["java", "-jar", "app.jar"]
